# Generated by Django 4.1.5 on 2025-12-27 16:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=False)),
                ('monthly_income', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fixed_expenses', models.JSONField(default=dict)),
                ('variable_expenses', models.JSONField(default=dict)),
                ('savings_investments', models.JSONField(default=dict)),
                ('yearly_income', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('annual_costs', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
