# Generated by Django 4.1.5 on 2025-12-27 17:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_budget'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('IMMEDIATE', 'Immediate (0-12 Months)'), ('SHORT', 'Short-Term (1-3 Years)'), ('MEDIUM', 'Medium-Term (3-7 Years)'), ('LONG', 'Long-Term (7+ Years)')], default='SHORT', max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, help_text='Why do I want it?')),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('current_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('target_date', models.DateField()),
                ('funding_strategy', models.TextField(blank=True, help_text='How will I fund it?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
