# Generated by Django 4.1.5 on 2025-12-26 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_loan'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='start_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
