# Generated by Django 4.1.5 on 2025-12-26 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_loan_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='is_property_loan',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='loan',
            name='resale_value_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
