# Generated by Django 4.1.5 on 2025-12-26 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_loan_is_property_loan_loan_resale_value_percentage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='resale_value_percentage',
        ),
        migrations.AddField(
            model_name='loan',
            name='resale_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
