# Generated by Django 4.1.5 on 2025-12-31 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_remove_loan_resale_value_percentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('Rent', 'Rent'), ('EMI', 'EMI'), ('Electricity', 'Electricity'), ('Water', 'Water'), ('Gas', 'Gas'), ('Internet', 'Internet'), ('Mobile Recharge', 'Mobile recharge'), ('DTH/Cable', 'DTH/Cable'), ('Groceries', 'Groceries'), ('Dining Out', 'Dining Out'), ('Transportation', 'Transportation'), ('Shopping', 'Clothing or Lifestyle or Shopping'), ('Insurance', 'Insurance'), ('Medicine', 'Medicine'), ('Tuition Fees', 'Tuition fees'), ('Entertainment', 'Entertainment'), ('Electronics', 'Electronics'), ('Furniture', 'Furniture'), ('Membership', 'Membership'), ('Emergency', 'Emergency Expense'), ('One-time', 'One-time Purchases'), ('Miscellaneous', 'Miscellaneous')], max_length=100),
        ),
        migrations.AlterField(
            model_name='income',
            name='type',
            field=models.CharField(choices=[('Salary', 'Salary'), ('Freelance', 'Freelance'), ('Commission', 'Commission'), ('Business', 'Business'), ('Partnership', 'Partnership'), ('Bonus', 'Bonus'), ('Interest', 'Interest'), ('Dividend', 'Dividend'), ('Capital Gains', 'Capital Gains'), ('Rental', 'Rental'), ('Franchise', 'Franchise'), ('Sponsorship', 'Sponsorship'), ('Pension', 'Pension'), ('Other', 'Other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='type',
            field=models.CharField(choices=[('Life', 'Life'), ('Health', 'Health/Medical'), ('Term', 'Term'), ('Vehicle', 'Vehicle'), ('Home', 'Home/Property'), ('Travel', 'Travel'), ('Business', 'Business')], max_length=50),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_type',
            field=models.CharField(choices=[('Home', 'Home'), ('Personal', 'Personal'), ('Vehicle', 'Vehicle'), ('Agriculture', 'Agriculture'), ('Gold', 'Gold & Asset-Backed'), ('Other', 'Other')], max_length=50),
        ),
    ]
