# Generated by Django 4.1.5 on 2025-12-31 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_alter_expense_category_alter_income_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='insurance',
            old_name='renewal_date',
            new_name='purchase_date',
        ),
    ]
